import Link from "next/link";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { createCaller } from "@/server/trpc/caller";

export default async function DashboardPage() {
  const caller = await createCaller();
  const { metrics, topOpportunities } = await caller.dashboard.overview();

  return (
    <main className="mx-auto flex w-full max-w-6xl flex-col gap-8 px-6 py-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight">
            Synergy Dashboard
          </h1>
          <p className="text-muted-foreground">
            Track collaboration opportunities across the WWH alliance.
          </p>
        </div>
        <Button asChild>
          <Link href="/intake">Add Company</Link>
        </Button>
      </div>

      <section className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Total Companies</CardDescription>
            <CardTitle className="text-3xl font-bold">
              {metrics.companies}
            </CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Active Needs</CardDescription>
            <CardTitle className="text-3xl font-bold">
              {metrics.needs}
            </CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Active Offers</CardDescription>
            <CardTitle className="text-3xl font-bold">
              {metrics.offers}
            </CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Total Opportunities</CardDescription>
            <CardTitle className="text-3xl font-bold">
              {metrics.opportunities}
            </CardTitle>
          </CardHeader>
        </Card>
      </section>

      <Card>
        <CardHeader>
          <CardTitle>Top Opportunities</CardTitle>
          <CardDescription>
            Highest scoring plays generated by the graph engine.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Opportunity</TableHead>
                <TableHead>Source</TableHead>
                <TableHead>Target</TableHead>
                <TableHead className="text-right">Score</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {topOpportunities.map((opportunity) => (
                <TableRow key={opportunity.id}>
                  <TableCell className="max-w-[240px]">
                    <div className="flex flex-col gap-1">
                      <span className="font-medium">
                        {opportunity.need?.title ?? opportunity.offer?.title ?? "Opportunity"}
                      </span>
                      <span className="text-xs text-muted-foreground">
                        {opportunity.breakdown?.summary ?? "Synergy match"}
                      </span>
                    </div>
                  </TableCell>
                  <TableCell>
                    <Link
                      className="text-sm font-medium text-primary hover:underline"
                      href={`/companies/${opportunity.source.id}`}
                    >
                      {opportunity.source.name}
                    </Link>
                  </TableCell>
                  <TableCell>
                    <Link
                      className="text-sm font-medium text-primary hover:underline"
                      href={`/companies/${opportunity.target.id}`}
                    >
                      {opportunity.target.name}
                    </Link>
                  </TableCell>
                  <TableCell className="text-right font-semibold">
                    {opportunity.score.toFixed(2)}
                  </TableCell>
                  <TableCell>
                    <Badge variant={opportunity.status === "OPEN" ? "secondary" : "outline"}>
                      {opportunity.status.replace("_", " ")}
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
              {topOpportunities.length === 0 && (
                <TableRow>
                  <TableCell colSpan={5} className="text-center text-muted-foreground">
                    No opportunities yet. Add companies or refresh the graph.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </main>
  );
}
